### ISSUE TITLE
Mejora de Código: Refactorizar

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2021-araya#9]
Se debería analizar la posibilidad de emplear menos líneas de código para realizar los dibujos.

Quizás si no hay un patrón de medidas (es decir, si no varía siempre en una misma distancia de px), se podría crear un array y parsear cada valor, para tomarlo y graficar.

Cualquier cosa coordinamos un horario de consulta previo al final para ver que sería conveniente.

**Comment by aaraya0** [comment]
Se utilizó una nueva función _draw_ para reducir las líneas de código en la función _Graficar_ (de 4 líneas por círculo a 1 sola línea por círculo)
